version: 2
jobs:
  build:
    working_directory: ~/homeday-blocks
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Update npm
          command: sudo npm i -g npm@5.6.0
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Build Storybook
          command: | 
            npm run build
            npm run storybook:build
      - persist_to_workspace:
          root: ~/homeday-blocks
          paths: 
            - storybook-static

  deploy:
    docker:
      - image: cibuilds/aws:1.16.43
    steps:
      - attach_workspace:
          at: ./build-storybook
      - run:
          name: Deploy to S3
          command: aws s3 sync build-storybook/storybook-static s3://hd-storybook/circle-ci/ --delete --region eu-central-1

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: develop